spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/computer_store
    username: yarik
    password: 0192837465Pq
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop